version: 2.1
orbs:
  node: circleci/node@1.1.6
  browser-tools: circleci/browser-tools@0.1.4
jobs:
  build-and-test:
    executor:
      name: node/default
    environment:
      CHROME_BIN: /usr/bin/google-chrome
    steps:
      - checkout
      - node/with-cache:
          steps:
            - browser-tools/install-browser-tools
            - run: npm install
            #- run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test